name: GKE Deployment

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

env:
  PROJECT_ID: ambient-hulling-391111
  CLUSTER_NAME: autopilot-cluster-1
  ZONE: your-zone
  IMAGE: cyrillknecht/sentiment-classification
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Configure Docker
      run: |
        docker pull ${{ env.IMAGE }}

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} 

    - name: Delete previous deployment
      run: |
        kubectl delete deployment  sentiment-webapp-deployment

    - name: Create new deployment
      run: |
        kubectl create deployment  sentiment-webapp-deployment --image=${{ env.IMAGE }}
