name: GKE Deployment

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

env:
  PROJECT_ID: ambient-hulling-391111
  CLUSTER_NAME: autopilot-cluster-1
  ZONE: europe-central2
  IMAGE: cyrillknecht/sentiment-classification
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }}  --zone ${{ env.ZONE }}

    - name: Delete previous deployment
      run: |
        kubectl delete deployment  sentiment-webapp-deployment

    - name: Create new deployment
      run: |
        kubectl create deployment  sentiment-webapp-deployment --image=${{ env.IMAGE }}
